name: build

on:
  push:
    branches: [ "*" ]

jobs:
  build-m2000-windows:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y mingw-w64 build-essential cmake zip curl tar
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src
    - name: Build
      run: cd build && make -j
    - name: Generate artifact name
      id: generate-name
      run: echo "artifact_name=M2000-snapshot-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    - name: Upload launcher
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.generate-name.outputs.artifact_name }}
        path: |
          build/M2000.exe
          build/allegro-5.2.dll
          build/allegro_primitives-5.2.dll
          build/allegro_image-5.2.dll
          build/allegro_audio-5.2.dll
          build/allegro_dialog-5.2.dll
          build/allegro_memfile-5.2.dll
          build/Default.fnt
          build/P2000ROM.bin
          build/BASIC.bin
